(require 'module-custom)
(require 'module-lsp)
(require 'module-tags)
(require 'module-git)
(require 'module-picture)

(setq wen-ai-aider-args '("--no-auto-commits" "--model" ""))
(setq wen-ai-aider-key-env "")
(setq wen-ai-aider-key "")
(setq wen-ai-gptel-groq-model 'deepseek-r1-distill-llama-70b)
(setq wen-ai-gptel-groq-key "")
(setq wen-ai-llm-gemini-key "")
(setq wen-ai-llm-gemini-model "")
(require 'module-ai)

(setq wen-obsidian-knowledge "~/Documents/Knowledge/")
(setq wen-obsidian-inbox "~/Documents/Tasks/")
(setq wen-obsidian-daily "~/Documents/Daily//")
(require 'module-obsidian)

(setq wen-hugo-github-repo "~/Documents/Hugo")
(setq wen-hugo-github-url "https://yourid.github.io")
(require 'module-hugo)
